=== mhamed-sayamik/gestion-absences/scholarite.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
    <xs:element name="Scholarite">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="enseignant" type="ensType" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="etudiant" type="etudiantType" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="module" type="moduleType" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="matiere" type="matiereType" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="note" type="noteType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="cin" type="xs:string"></xs:element>
    <xs:element name="sexe">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="Masculin|Feminin"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="nom" type="xs:string"></xs:element>
    <xs:element name="prenom" type="xs:string"></xs:element>
    <xs:element name="tele" >
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="type" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="fix"/>
                                <xs:enumeration value="portable"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="email">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="type" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="personnel" />
                                <xs:enumeration value="academique" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
            
        </xs:complexType>
    </xs:element>
    <xs:complexType name="ensType" mixed="true">
        <xs:sequence>
            <xs:element ref="cin"></xs:element>
            <xs:element ref="sexe"></xs:element>
            <xs:element ref="nom"></xs:element>
            <xs:element ref="prenom"></xs:element>
            <xs:element ref="tele" minOccurs="1" maxOccurs="unbounded"></xs:element>
            <xs:element ref="email" minOccurs="1" maxOccurs="unbounded"></xs:element>
            <xs:element name="specialite" type="xs:string"></xs:element>
            <xs:element name="departement">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="GI|TM|TIMQ|GIM"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="numSomme" type="xs:ID" use="required"/>
    </xs:complexType>
    <xs:complexType name="etudiantType" mixed="true">
        <xs:sequence>
            <xs:element ref="cin"></xs:element>
            <xs:element ref="sexe"></xs:element>
            <xs:element ref="nom"></xs:element>
            <xs:element ref="prenom"></xs:element>
            <xs:element ref="tele" minOccurs="1" maxOccurs="unbounded"></xs:element>
            <xs:element ref="email" minOccurs="1" maxOccurs="unbounded"></xs:element>
            <xs:element name="dateNaissance" type="xs:date"></xs:element>
            <xs:element name="adresse" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="rue" type="xs:string"></xs:element>
                        <xs:element name="numero" type="xs:integer"></xs:element>
                        <xs:element name="ville" type="xs:string"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="numInsc" type="xs:ID" use="required"/>
    </xs:complexType>
    <xs:complexType name="moduleType">
        <xs:sequence>
            <xs:element ref="nom"></xs:element>
            <xs:element name="coordonnateur" type="xs:IDREF"></xs:element>
        </xs:sequence>
        <xs:attribute name="codeModule" type="xs:ID" use="required"/>
    </xs:complexType>
    <xs:complexType name="matiereType">
        <xs:sequence>
            <xs:element name="intitule" type="xs:string"></xs:element>
            <xs:element name="coefficient" type="xs:float"></xs:element>
            <xs:element name="enseignant" type="xs:IDREF"></xs:element>
            <xs:element name="module" type="xs:IDREF"></xs:element>
        </xs:sequence>
        <xs:attribute name="codeMatiere" type="xs:ID" use="required"/>
    </xs:complexType>
    <xs:complexType name="noteType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="DS" />
                            <xs:enumeration value="EF" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="etudiant" type="xs:IDREF" use="required"/>
                <xs:attribute name="matiere" type="xs:IDREF" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== mhamed-sayamik/gestion-absences/scholarite.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./qu1.xsl"?>
<Scholarite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="./scholarite.xsd">
    <enseignant numSomme="E01">
        <cin>HH76692</cin>
        <sexe>Masculin</sexe>
        <nom>ESSALIH </nom>
        <prenom>Mohammed</prenom>
        <tele type="fix">05839938989</tele>
        <tele type="portable">058399388</tele>
        <email type="personnel">Mohammed@gmail.com</email>
        <email type="academique">Mohammed@edu.uca.ma</email>
        <specialite>Administration des systemes et reseaux</specialite>
        <departement>GI</departement>
    </enseignant>
    <enseignant  numSomme="E02">
        <cin>HH76691</cin>
        <sexe>Masculin</sexe>
        <nom>EL ALAOUI</nom>
        <prenom>Othmane</prenom>
        <tele type="fix">0583993895</tele>
        <tele type="portable">06839938877</tele>
        <email type="personnel">Othmane@gmail.com</email>
        <email type="academique">Othmane@edu.uca.ma</email>
        <specialite>Bases de données avancées</specialite>
        <departement>GI</departement>
    </enseignant>
    <enseignant  numSomme="E03">
        <cin>HH76691</cin>
        <sexe>Masculin</sexe>
        <nom>EL KOURRI</nom>
        <prenom>Rachid</prenom>
        <tele type="fix">0583993895</tele>
        <tele type="portable">06839938877</tele>
        <email type="personnel">Rachid@gmail.com</email>
        <email type="academique">Rachid@edu.uca.ma</email>
        <specialite>Francais</specialite>
        <departement>GI</departement>
    </enseignant>
    <enseignant  numSomme="E04">
        <cin>HH76691</cin>
        <sexe>Masculin</sexe>
        <nom>BELFKIH</nom>
        <prenom>Khalid</prenom>
        <tele type="fix">0583993895</tele>
        <tele type="portable">06839938877</tele>
        <email type="personnel">Khalid@gmail.com</email>
        <email type="academique">Khalid@edu.uca.ma</email>
        <specialite>Anglais</specialite>
        <departement>GI</departement>
    </enseignant>
    <enseignant  numSomme="E05">
        <cin>HH76691</cin>
        <sexe>Masculin</sexe>
        <nom>BASSAKRI</nom>
        <prenom>BASSAKRI</prenom>
        <tele type="fix">0583993895</tele>
        <tele type="portable">06839938877</tele>
        <email type="personnel">BASSAKRI@gmail.com</email>
        <email type="academique">BASSAKRI@edu.uca.ma</email>
        <specialite>Culture</specialite>
        <departement>GI</departement>
    </enseignant>

    <etudiant  numInsc="ET00">
        <cin>HH87236</cin>
        <sexe>Masculin</sexe>
        <nom>Elkarouaoui</nom>
        <prenom>Ali</prenom>
        <tele type="fix">05839938989</tele>
        <tele type="portable">058399388</tele>
        <email type="personnel">ali@gmail.com</email>
        <email type="academique">ali@edu.uca.ma</email>
        <dateNaissance>2002-08-20</dateNaissance>
        <adresse>
            <rue>jamal eddora</rue>
            <numero>20</numero>
            <ville>Safi</ville>
        </adresse>
    </etudiant>
    <etudiant  numInsc="ET01">
        <cin>HH87236</cin>
        <sexe>Masculin</sexe>
        <nom>Elkarouaoui1</nom>
        <prenom>Ali1</prenom>
        <tele type="fix">05839938989</tele>
        <tele type="portable">058399388</tele>
        <email type="personnel">ali1@gmail.com</email>
        <email type="academique">ali1@edu.uca.ma</email>
        <dateNaissance>2002-08-20</dateNaissance>
        <adresse>
            <rue>jamal eddora</rue>
            <numero>20</numero>
            <ville>Safi</ville>
        </adresse>
    </etudiant>

    <module codeModule="Mod09">
        <nom>Administration des systemes et reseaux</nom>
        <coordonnateur>E01</coordonnateur>
    </module>
    <module codeModule="Mod07">
        <nom>Bases de données avancées</nom>
        <coordonnateur>E02</coordonnateur>
    </module>
    <module codeModule="Mod01">
        <nom>Langues et cultures</nom>
        <coordonnateur>E03</coordonnateur>
    </module>

    <matiere codeMatiere="M00">
        <intitule>Administration des systemes et reseaux</intitule>
        <coefficient>100</coefficient>
        <enseignant>E01</enseignant>
        <module>Mod09</module>
    </matiere>
    <matiere codeMatiere="M01">
        <intitule>Bases de données avancées</intitule>
        <coefficient>100</coefficient>
        <enseignant>E02</enseignant>
        <module>Mod07</module>
    </matiere>
    <matiere codeMatiere="M02">
        <intitule>Francais</intitule>
        <coefficient>35</coefficient>
        <enseignant>E03</enseignant>
        <module>Mod01</module>
    </matiere>
    <matiere codeMatiere="M03">
        <intitule>Anglais</intitule>
        <coefficient>35</coefficient>
        <enseignant>E04</enseignant>
        <module>Mod01</module>
    </matiere>
    <matiere codeMatiere="M04">
        <intitule>Culture</intitule>
        <coefficient>30</coefficient>
        <enseignant>E05</enseignant>
        <module>Mod01</module>
    </matiere>
    <note type="DS" etudiant="ET00" matiere="M00">20</note>
    <note type="EF" etudiant="ET00" matiere="M00">19</note>
    <note type="EF" etudiant="ET01" matiere="M01">19</note>
</Scholarite>
