=== mhamed-sayamik/gestion-absences/xsd_file.xsd
<?xml version="1.0" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ESTS" >
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="Roles" type="RolesType"></xs:element>
                <xs:element name="Users" type="UsersType"></xs:element>
                <xs:element name="Permissions" type="PermissionsType"></xs:element>
                <xs:element name="Groupes" type="GroupesType"></xs:element>
                <xs:element name="Departements" type="DepartementsType"></xs:element>
                <xs:element name="Filieres" type="FilieresType"></xs:element>
                <xs:element name="Niveaux" type="NiveauxType"></xs:element>
                <xs:element name="Etudiants" type="EtudiantsType"></xs:element>
                <xs:element name="Seances" type="SeancesType"></xs:element>
                <xs:element name="Matieres" type="MatieresType"></xs:element>
                <xs:element name="Semestres" type="SemestresType"></xs:element>
                <xs:element name="Modules" type="ModulesType"></xs:element>
                <xs:element name="roles_permissions" type="roles_permissionsType"></xs:element>
                <xs:element name="filieres_niveaux" type="filieres_niveauxType"></xs:element>
                <xs:element name="access" type="accessType"></xs:element>
                <xs:element name="abscences" type="abscencesType"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- //////////////////7 ELEMENT NOM GLOBAL ///////////////// -->
    <xs:element name="nomType" type="xs:string"></xs:element>

    <!-- ////////////////////// ELEMENT Roles /////////////// -->
    <xs:complexType name="RolesType">
        <xs:sequence>
            <xs:element name="role" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="id" type="xs:ID"></xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ////////////////////// ELEMENT Roles /////////////// -->

    <xs:complexType name="UsersType">
        <xs:sequence>
            <xs:element name="user" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="login" type="xs:ID"></xs:element>
                        <xs:element name="password" type="xs:string"></xs:element>
                        <xs:element name="Nom" type="xs:string"></xs:element>
                        <xs:element name="Prenom" type="xs:string"></xs:element>
                        <xs:element name="id_Roles" type="xs:IDREF"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ////////////////////// ELEMENT Permissions /////////////// -->
    <xs:complexType name="PermissionsType">
        <xs:sequence>
            <xs:element name="permission" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nom" type="xs:string"></xs:element>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:ID"></xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ////////////////////// ELEMENT Groupes /////////////// -->
    <xs:complexType name="GroupesType">
        <xs:sequence>
            <xs:element name="groupe" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="id" type="xs:ID"></xs:attribute>
                    <xs:attribute name="numero" type="xs:integer"></xs:attribute>
                    <xs:attribute name="id_Filieres" type="xs:IDREF"></xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ////////////////////// ELEMENT Departements /////////////// -->
    <xs:complexType name="DepartementsType">
        <xs:sequence>
            <xs:element name="departement" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="id" type="xs:ID"></xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ////////////////////// ELEMENT Filieres /////////////// -->
    <xs:complexType name="FilieresType">
        <xs:sequence>
            <xs:element name="filiere" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nom" type="xs:string"></xs:element>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:ID"></xs:attribute>
                    <xs:attribute name="id_Departements" type="xs:IDREF"></xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ////////////////////// ELEMENT Niveaux /////////////// -->
    <xs:complexType name="NiveauxType">
        <xs:sequence>
            <xs:element name="niveau" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="id" type="xs:ID"></xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ////////////////////// ELEMENT Etudiants /////////////// -->
    <xs:complexType name="EtudiantsType">
        <xs:sequence>
            <xs:element name="etudiant" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nom" type="xs:string"></xs:element>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:ID"></xs:attribute>
                    <xs:attribute name="id_Groupes" type="xs:IDREF"></xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ////////////////////// ELEMENT Seances /////////////// -->
    <xs:complexType name="SeancesType">
        <xs:sequence>
            <xs:element name="seance" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="duree" type="xs:integer"></xs:element>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:ID"></xs:attribute>
                    <xs:attribute name="numero" type="xs:integer"></xs:attribute>
                    <xs:attribute name="jour" type="xs:integer"></xs:attribute>
                    <xs:attribute name="semaine" type="xs:integer"></xs:attribute>
                    <xs:attribute name="semestre" type="xs:integer"></xs:attribute>
                    <xs:attribute name="id_Matieres" type="xs:IDREF"></xs:attribute>
                    <xs:attribute name="id_Groupes" type="xs:IDREF"></xs:attribute>
                    <xs:attribute name="enregistre">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="oui"/>
                                <xs:enumeration value="non"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ////////////////////// ELEMENT Matieres /////////////// -->
    <xs:complexType name="MatieresType">
        <xs:sequence>
            <xs:element name="matiere" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nom" type="xs:string"></xs:element>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:ID"></xs:attribute>
                    <xs:attribute name="id_module" type="xs:IDREF"></xs:attribute>
                    <xs:attribute name="id_Filieres" type="xs:IDREF"></xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ////////////////////// ELEMENT Groupes /////////////// -->
    <xs:complexType name="SemestresType">
        <xs:sequence>
            <xs:element name="semestre" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="id" type="xs:ID"></xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ////////////////////// ELEMENT Modules /////////////// -->
    <xs:complexType name="ModulesType">
        <xs:sequence>
            <xs:element name="module" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="id" type="xs:ID"></xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ////////////////////// ELEMENT roles_permissions /////////////// -->
    <xs:complexType name="roles_permissionsType">
        <xs:sequence>
            <xs:element name="role_permission" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="id_Permissions" type="xs:IDREF"></xs:attribute>
                    <xs:attribute name="id_Roles" type="xs:IDREF"></xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ////////////////////// ELEMENT filieres_niveaux /////////////// -->
    <xs:complexType name="filieres_niveauxType">
        <xs:sequence>
            <xs:element name="filiere_niveau" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="id_Filieres" type="xs:IDREF"></xs:attribute>
                    <xs:attribute name="id_Niveaux" type="xs:IDREF"></xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ////////////////////// ELEMENT access /////////////// -->
    <xs:complexType name="accessType">
        <xs:sequence>
            <xs:element name="user_matiere" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="login_user" type="xs:IDREF"></xs:attribute>
                    <xs:attribute name="id_Matieres" type="xs:IDREF"></xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- ////////////////////// ELEMENT abscences /////////////// -->
    <xs:complexType name="abscencesType">
        <xs:sequence>
            <xs:element name="abscence" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="id_Etudiants" type="xs:IDREF"></xs:attribute>
                    <xs:attribute name="id_Seances" type="xs:IDREF"></xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>



</xs:schema>

=== mhamed-sayamik/gestion-absences/ESTS1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ESTS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd_file.xsd">
  <!-- /////////////////////////// TABLE ROLE /////////////////////////////////// -->
  <Roles>
    <role id="R1">Professeur</role>
    <role id="R2">Coordonnateur</role>
    <role id="R3">Chef departement</role>
    <role id="R4">Agents de scholarite</role>
    <role id="R5">Admin</role>
  </Roles>
  <!-- /////////////////////////// TABLE Users /////////////////////////////////// -->
  <Users>
    <!-- ////////////////////////// Professeurs ///////////////////////////////// -->
    <user>
      <login>Prof7</login>
      <password>admin</password>
      <Nom>BAYAR</Nom>
      <Prenom>Abdelouahad</Prenom>
      <id_Roles>R1</id_Roles>
    </user>
    <user>
      <login>Prof9</login>
      <password>password789</password>
      <Nom>Bob</Nom>
      <Prenom>Smith</Prenom>
      <id_Roles>R1</id_Roles>
    </user>
    <user>
      <login>Prof10</login>
      <password>password789</password>
      <Nom>Bob</Nom>
      <Prenom>Smith</Prenom>
      <id_Roles>R1</id_Roles>
    </user>
    <!-- ////////////////////////// Coordonnateurs ///////////////////////////////// -->
    <user>
      <login>Coordonnateur1</login>
      <password>admin</password>
      <Nom>DOE</Nom>
      <Prenom>ABDERRAHMANE</Prenom>
      <id_Roles>R2</id_Roles>
    </user>
    <user>
      <login>Coordonnateur2</login>
      <password>pwd1234</password>
      <Nom>jalil</Nom>
      <Prenom>Smith</Prenom>
      <id_Roles>R2</id_Roles>
    </user>
    <user>
      <login>Coordonnateur3</login>
      <password>pwd12345</password>
      <Nom>jalil</Nom>
      <Prenom>Smith</Prenom>
      <id_Roles>R2</id_Roles>
    </user>
    <!-- ////////////////////////// Chef departements ///////////////////////////////// -->
    <user>
      <login>ChefDept2</login>
      <password>pwd1234</password>
      <Nom>jalil</Nom>
      <Prenom>Smith</Prenom>
      <id_Roles>R3</id_Roles>
    </user>
    <!-- ////////////////////////// Agents de scholarite ///////////////////////////////// -->
    <user>
      <login>Agent_scholarite1</login>
      <password>pwd123</password>
      <Nom>John</Nom>
      <Prenom>Doe</Prenom>
      <id_Roles>R4</id_Roles>
    </user>
    <user>
      <login>Agent_scholarite3</login>
      <password>pwd12345</password>
      <Nom>jalil</Nom>
      <Prenom>Smith</Prenom>
      <id_Roles>R4</id_Roles>
    </user>
    <user>
      <login>prof22</login>
      <password>134</password>
      <Nom>DOE</Nom>
      <Prenom>JOHN</Prenom>
      <id_Roles>R1</id_Roles>
    </user>
    <user>
      <login>Prof11</login>
      <password>pwd@1890-</password>
      <Nom>DOE1</Nom>
      <Prenom>ABDERRAHMANE</Prenom>
      <id_Roles>R1</id_Roles>
    </user>
    <user>
      <login>ChefDept3</login>
      <password>pwd0865_oi</password>
      <Nom>DOE1</Nom>
      <Prenom>Abdelouahad</Prenom>
      <id_Roles>R3</id_Roles>
    </user>
    <!-- ////////////////////////////////// ADMIN //////////////////////////////////////////////// -->
    <user>
      <login>admin</login>
      <password>admin</password>
      <Nom>ELKAROUAOUI</Nom>
      <Prenom>Ali</Prenom>
      <id_Roles>R5</id_Roles>
    </user>
    <user>
      <login>prof215</login>
      <password>qwtdt43</password>
      <Nom>DOE</Nom>
      <Prenom>ali</Prenom>
      <id_Roles>R1</id_Roles>
    </user>
  </Users>
  <!-- /////////////////////////// TABLE Permissions /////////////////////////////////// -->
  <Permissions>
    <permission id="P1">
      <nom>Faire l'absence</nom>
    </permission>
    <permission id="P2">
      <nom>Afficher les absents</nom>
    </permission>
    <permission id="P3">
      <nom>Editer absence</nom>
    </permission>
    <permission id="P4">
      <nom>Ajouter utilisateur</nom>
    </permission>
    <permission id="P5">
      <nom>Supprimer utilisateur</nom>
    </permission>
  </Permissions>
  <!-- /////////////////////////// TABLE Groupes /////////////////////////////////// -->
  <Groupes>
    <groupe id="G1" numero="1" id_Filieres="F1"/>
    <groupe id="G2" numero="2" id_Filieres="F1"/>
  </Groupes>
  <!-- /////////////////////////// TABLE Departements /////////////////////////////////// -->
  <Departements>
    <departement id="D1">Computer Science</departement>
    <departement id="D2">Mathematics</departement>
  </Departements>
  <!-- /////////////////////////// TABLE Filieres /////////////////////////////////// -->
  <Filieres>
    <filiere id="F1" id_Departements="D2">
      <nom>ISIR</nom>
    </filiere>
    <filiere id="F2" id_Departements="D2">
      <nom>GI</nom>
    </filiere>
  </Filieres>
  <!-- /////////////////////////// TABLE Niveaux /////////////////////////////////// -->
  <Niveaux>
    <niveau id="N1">Undergraduate</niveau>
    <niveau id="N2">Graduate</niveau>
  </Niveaux>
  <!-- /////////////////////////// TABLE Etudiants /////////////////////////////////// -->
  <Etudiants>
    <etudiant id="E9" id_Groupes="G1">
      <nom>Ahmed</nom>
    </etudiant>
    <etudiant id="E1" id_Groupes="G1">
      <nom>Alice</nom>
    </etudiant>
    <etudiant id="E2" id_Groupes="G1">
      <nom>Bob</nom>
    </etudiant>
    <etudiant id="E3" id_Groupes="G2">
      <nom>Charlie</nom>
    </etudiant>
    <etudiant id="E4" id_Groupes="G2">
      <nom>Dexter</nom>
    </etudiant>
  </Etudiants>
  <!-- /////////////////////////// TABLE Seances /////////////////////////////////// -->
  <Seances>
    <seance id="S1" numero="1" jour="1" semaine="1" semestre="1" id_Matieres="MA1" id_Groupes="G1" enregistre="oui">
      <duree>60</duree>
    </seance>
    <seance id="S2" numero="2" jour="1" semaine="1" semestre="1" id_Matieres="MA3" id_Groupes="G1" enregistre="oui">
      <duree>60</duree>
    </seance>
    <seance id="S3" numero="3" jour="6" semaine="1" semestre="2" id_Matieres="MA2" id_Groupes="G2" enregistre="oui">
      <duree>60</duree>
    </seance>
    <seance id="S4" numero="4" jour="6" semaine="1" semestre="2" id_Matieres="MA4" id_Groupes="G2" enregistre="oui">
      <duree>60</duree>
    </seance>
  </Seances>
  <!-- /////////////////////////// TABLE Matieres /////////////////////////////////// -->
  <Matieres>
    <matiere id="MA1" id_module="MO1" id_Filieres="F2">
      <nom>mat1</nom>
    </matiere>
    <matiere id="MA2" id_module="MO1" id_Filieres="F2">
      <nom>mat12</nom>
    </matiere>
    <matiere id="MA3" id_module="MO1" id_Filieres="F1">
      <nom>Matiere 3</nom>
    </matiere>
    <matiere id="MA4" id_module="MO1" id_Filieres="F1">
      <nom>Matiere 4</nom>
    </matiere>
    <matiere id="MA5" id_module="MO1" id_Filieres="F2">
      <nom>ml</nom>
    </matiere>
    <matiere id="MA6" id_module="MO2" id_Filieres="F1">
      <nom>deeplearning</nom>
    </matiere>
    <matiere id="MA7" id_module="MO1" id_Filieres="F1">
      <nom>AI</nom>
    </matiere>
  </Matieres>
  <!-- /////////////////////////// TABLE Semestres /////////////////////////////////// -->
  <Semestres>
    <semestre id="SE1"/>
    <semestre id="SE2"/>
  </Semestres>
  <!-- /////////////////////////// TABLE Modules /////////////////////////////////// -->
  <Modules>
    <module id="MO1">Introduction to Computer Science</module>
    <module id="MO2">Introduction to Calculus</module>
  </Modules>
  <!-- /////////////////////////// TABLE roles_permissions /////////////////////////////////// -->
  <roles_permissions>
    <role_permission id_Permissions="P1" id_Roles="R1"/>
    <role_permission id_Permissions="P2" id_Roles="R1"/>
    <role_permission id_Permissions="P3" id_Roles="R1"/>
    <role_permission id_Permissions="P4" id_Roles="R1"/>
    <role_permission id_Permissions="P5" id_Roles="R1"/>
    <role_permission id_Permissions="P1" id_Roles="R3"/>
  </roles_permissions>
  <!-- /////////////////////////// TABLE filieres_niveaux /////////////////////////////////// -->
  <filieres_niveaux>
    <filiere_niveau id_Filieres="F1" id_Niveaux="N1"/>
    <filiere_niveau id_Filieres="F2" id_Niveaux="N2"/>
  </filieres_niveaux>
  <!-- /////////////////////////// TABLE access /////////////////////////////////// -->
  <access>
    <user_matiere login_user="Prof7" id_Matieres="MA1"/>
    <user_matiere login_user="Prof7" id_Matieres="MA3"/>
  </access>
  <!-- /////////////////////////// TABLE abscences /////////////////////////////////// -->
  <abscences>
    <abscence id_Etudiants="E3" id_Seances="S2"/>
    <abscence id_Etudiants="E9" id_Seances="S1"/>
    <abscence id_Etudiants="E2" id_Seances="S1"/>
    <abscence id_Etudiants="E4" id_Seances="S3"/>
  </abscences>
</ESTS>
